# Generated by Django 5.1.4 on 2024-12-18 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('iso_date', models.DateField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
                ('primary_type', models.CharField(max_length=100, null=True)),
                ('types', models.JSONField(null=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('url_id', models.CharField(blank=True, max_length=255, null=True)),
                ('locations', models.CharField(max_length=255, null=True)),
                ('states', models.JSONField(blank=True, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='holivibeapp.country')),
            ],
        ),
    ]
